site_name: OPNSky Docs
site_url: https://mrfrederic.github.io/opnsky-docs/
theme:
  name: material
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.sections
    - content.code.annotate
    - content.action.edit
    - content.action.view
    - content.footnotes
    - content.tabs.link
    - content.tooltips
    - palette.toggle
  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

repo_url: https://github.com/mrfrederic/opnsky-docs
edit_uri: blob/main/docs/

plugins:
  - search
  - neoteroi.mkdocsoad:
      use_pymdownx: true
  - git-revision-date-localized:
      fallback_to_build_date: true
      enable_creation_date: true
      locale: en
  - awesome-pages